# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(848, 472)
        MainWindow.setStyleSheet("font: 75 8pt \"Courier\";\n"
"background-color: rgb(237, 250, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AccidentsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.AccidentsBtn.setGeometry(QtCore.QRect(70, 170, 141, 51))
        self.AccidentsBtn.setStyleSheet(" background-color: #2c3e50;\n"
"border-radius: 20px;\n"
"color: white;\n"
"    border: none;\n"
"\n"
"    padding: 10px 20px;\n"
"")
        self.AccidentsBtn.setObjectName("AccidentsBtn")
        self.DriversBtn = QtWidgets.QPushButton(self.centralwidget)
        self.DriversBtn.setGeometry(QtCore.QRect(240, 170, 141, 51))
        self.DriversBtn.setStyleSheet(" background-color: #2c3e50;\n"
"border-radius: 20px;\n"
"color: white;\n"
"    border: none;\n"
"\n"
"    padding: 10px 20px;\n"
"")
        self.DriversBtn.setObjectName("DriversBtn")
        self.FuelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.FuelBtn.setGeometry(QtCore.QRect(410, 170, 141, 51))
        self.FuelBtn.setStyleSheet(" background-color: #2c3e50;\n"
"border-radius: 20px;\n"
"color: white;\n"
"    border: none;\n"
"\n"
"    padding: 10px 20px;\n"
"")
        self.FuelBtn.setObjectName("FuelBtn")
        self.InspectionsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.InspectionsBtn.setGeometry(QtCore.QRect(580, 170, 141, 51))
        self.InspectionsBtn.setStyleSheet(" background-color: #2c3e50;\n"
"border-radius: 20px;\n"
"color: white;\n"
"    border: none;\n"
"\n"
"    padding: 10px 20px;\n"
"")
        self.InspectionsBtn.setObjectName("InspectionsBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AccidentsBtn.setText(_translate("MainWindow", "Доктора"))
        self.DriversBtn.setText(_translate("MainWindow", "Пациенты"))
        self.FuelBtn.setText(_translate("MainWindow", "Мед.истр"))
        self.InspectionsBtn.setText(_translate("MainWindow", "Диагнозы"))
